config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users

  root 'homes#top'
  get 'home/about' => 'homes#about'

  resources :books, only:[:index, :show, :edit, :create, :update, :destroy] do
   resource :favorites, only: [:create, :destroy]
   resource :book_comments, only: [:create, :destroy]
  end

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  get "search" => "searches#search"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name,  presence: true, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def User.search(search, user_or_book, how_search)
    if user_or_book == "1"
      if how_search == "1"
        User.where(['name LIKE ?',"#{search}"])
      elsif how_search == "2"
        User.where(['name LIKE ?',"#{search}%"])
      elsif how_search == "3"
        User.where(['name LIKE ?',"%#{search}"])
      elsif how_search == "4"
        User.where(['name LIKE ?',"%#{search}%"])
      else
        User.all
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:update,:edit]

  def show
    @user  = User.find(params[:id])
    @books = @user.books
    @book  = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
    @users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
    @book  = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
    @user = current_user
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user  = User.find(params[:id])
    @books = @user.books
    @book  = Book.new
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class='table'>
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:"100x100") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>

		<tr>
			<th>follows</th>
			<th>
			  <%= link_to follows_user_path(user) do %>
			  <%= user.followings.count %>
			  <% end %>
			</th>
		</tr>

		<tr>
			<th>followers</th>
      <th>
        <%= link_to followers_user_path(user) do %>
        <%= user.followers.count %>
        <% end %>
      </th>
		</tr>
</table>

app/views/users/edit.html.erb
<div class='body'>
  <div class='conteiner'>
    <div clsaa='row'>
      <div class='col-md-offset-1 col-md-6'>

        <h2>User info</h2>
        <%= form_for(@user) do |f| %>

        <!-- エラーメッセージ表示-->
        <%= render "template/error_messages" ,obj:@user %>
        <!-- エラーメッセージ表示-->

        <div class="field">
	        <%= f.label :name %>
	        <%= f.text_field :name, class: "name" %>

        </div><br>

        <div class="field">
	        <%= f.label :image %>
	        <%= f.attachment_field :profile_image, class: "user_image" %>
        </div><br>

        <div class="field">
	        <%= f.label :introduction %>
	        <%= f.text_area :introduction, class: "introduction" %>
        </div><br>

        <div class="actions">
	        <%= f.submit %>
        </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

<footer>
<%= render "template/footer" %>
</footer>

app/views/users/followers.html.erb
<div class='body'>
  <div class='conteiner'>
    <div clsaa='row'>
      <div class='col-md-offset-1 col-md-6'>

      	 <h2>Users Followers</h2>
        <table class="table">
	        <thead>
		      <tr>
			      <th>image</th>
			      <th>name</th>
			      <th colspan="3"></th>
		      </tr>
	        </thead>

	        <tbody>
		        <% @users.each do |user| %>
		      <tr>
			      <td>
                <%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:"50x50") %>
            </td>
			      <td>
              <%= user.name%>
            </td>
            <td>
            <td>
              <p>フォロー数：<%=  user.followings.count %><p>
            </td>
            <td>
              <p>フォロワー数：<%= user.followers.count %><p>
            </td>
            <td>
              <% if user.followed_by?(current_user) %>
                <%= link_to 'フォローを外す',user_relationships_path(user_id:user.id), method: :delete %>
              <% else %>
                <%= link_to 'フォローする',user_relationships_path(user_id:user.id),method: :post %>
              <% end %>
            </td>
			      <td>
              <%= link_to "Show", user, class: "user_#{user.id}" %>
            </td>
		      </tr>
		      <% end %>
	        </tbody>
        </table>

      </div>
    </div>
  </div>
</div>
<footer>
<%= render "template/footer" %>
</footer>

app/views/users/follows.html.erb
<div class='body'>
  <div class='conteiner'>
    <div clsaa='row'>
      <div class='col-md-offset-1 col-md-6'>

      	<h2>Users Follows</h2>
        <table class="table">
	        <thead>
		      <tr>
			      <th>image</th>
			      <th>name</th>
			      <th colspan="3"></th>
		      </tr>
	        </thead>

	        <tbody>
		        <% @users.each do |user| %>
		      <tr>
			      <td>
                <%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:"50x50") %>
            </td>
			      <td>
              <%= user.name%>
            </td>
            <td>
            <td>
              <p>フォロー数：<%=  user.followings.count %><p>
            </td>
            <td>
              <p>フォロワー数：<%= user.followers.count %><p>
            </td>
            <td>
              <% if user.followed_by?(current_user) %>
                <%= link_to 'フォローを外す',user_relationships_path(user_id:user.id), method: :delete %>
              <% else %>
                <%= link_to 'フォローする',user_relationships_path(user_id:user.id),method: :post %>
              <% end %>
            </td>
			      <td>
              <%= link_to "Show", user, class: "user_#{user.id}" %>
            </td>
		      </tr>
		      <% end %>
	        </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

<footer>
<%= render "template/footer" %>
</footer>

app/views/users/index.html.erb
<div class='body'>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3'>

        <h2>User info</h2>
        <%= render 'profile', user: current_user %>
        <!--メモ 右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

        <div class='row'>
          <% if @user.followed_by?(current_user) %>
            <%= link_to 'フォローを外す',user_relationships_path(user_id:@user.id), method: :delete, class: "btn btn-primary col-xs-6" %>
          <% else %>
            <%= link_to 'フォローする',user_relationships_path(user_id:@user.id),method: :post, class: "btn btn-success col-xs-6" %>
          <% end %>
        </div>

        <h2>New book</h2>
        <%= render 'books/newform', book: @book %>

      </div>

      <div class='col-xs-9'>

        <h2>Users</h2>
        <!--users一覧 -->
        <table class="table">
	        <thead>
		      <tr>
			      <th>image</th>
			      <th>name</th>
			      <th colspan="3"></th>
		      </tr>
	        </thead>

	        <tbody>
		        <% @users.each do |user| %>
		      <tr>
			      <td>
                <%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:"50x50") %>
            </td>
			      <td>
              <%= user.name%>
            </td>
            <td>
            <td>
              <p>フォロー数：<%=  user.followings.count %><p>
            </td>
            <td>
              <p>フォロワー数：<%= user.followers.count %><p>
            </td>
            <td>
              <% if user.followed_by?(current_user) %>
                <%= link_to 'フォローを外す',user_relationships_path(user_id:user.id), method: :delete %>
              <% else %>
                <%= link_to 'フォローする',user_relationships_path(user_id:user.id),method: :post %>
              <% end %>
            </td>
			      <td>
              <%= link_to "Show", user, class: "user_#{user.id}" %>
            </td>
		      </tr>
		      <% end %>
	        </tbody>
        </table>
        <!--users一覧 -->

      </div>
    </div>
  </div>
</div>

<footer>
<%= render "template/footer" %>
</footer>

app/views/users/show.html.erb
<div class='body'>
	<div class='container'>
    <div class='row'>
      <div class='col-xs-3'>

        <h2>User info</h2>
        <%= render 'profile', user: @user %>
        <!--同コントローラーのviewで表示ならusersは省略可 -->

          <div class='row'>
	          <%= link_to '',edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %>
          </div>

        <h2>New book</h2>
        <%= render 'books/newform', book: @book %>

      </div>

      <div class='col-xs-9'>

        <h2>Books</h2>
        <!--books一覧 -->
        <table class="table table-hover table-inverse">
	        <thead>
		      <tr>
			      <th></th>
			      <th>Title</th>
			      <th>Opinion</th>
			      <th colspan="3"></th>
		      </tr>
	        </thead>

	        <tbody>
		      <% @books.each do |book| %>

		      <tr>
			      <td>
				      <%= link_to (book.user) do %>
				      <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:"50x50") %>
				      <% end %>
			      </td>
			      <td>
			      	<%= link_to book.title,book, class: "book_#{book.id}" %>
			      </td>
			      <td>
			      	<%= book.body %>
			      </td>
			      <td>
			      	<p>コメント数：<%= book.book_comments.count %><p>
			      </td>
		      </tr>
		      <% end %>
	        </tbody>
        </table>
        <!--books一覧 -->
      </div>

    </div>
  </div>
</div>

<footer>
<%= render "template/footer" %>
</footer>