config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users

  root 'homes#top'
  get 'home/about' => 'homes#about'

  resources :books, only:[:index, :show, :edit, :create, :update, :destroy] do
   resource :favorites, only: [:create, :destroy]
   resource :book_comments, only: [:create, :destroy]
  end

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  get "search" => "searches#search"

end

app/models/book.rb
class Book < ApplicationRecord
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	belongs_to :user

	has_many :favorites,dependent: :destroy
  def favorited_by?(user)
  	favorites.where(user_id: user.id).exists?
  end

  has_many :book_comments,dependent: :destroy

  def Book.search(search, user_or_book, how_search)
    if user_or_book == "2"
      if how_search == "1"
        Book.where(['title LIKE ?',"#{search}"])
      elsif how_search == "2"
        Book.where(['title LIKE ?',"#{search}%"])
      elsif how_search == "3"
        Book.where(['title LIKE ?',"%#{search}"])
      elsif how_search == "4"
        Book.where(['title LIKE ?',"%#{search}%"])
      else
        Book.all
      end
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :baria_user, only: [:edit]

  def show
    @book         = Book.new
    @books        = Book.find(params[:id])
    @user         = @books.user
    @book_comment = BookComment.new
    @book_comments = @books.book_comments
  end

  def index
    @books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book  = Book.new
    @user = current_user
  end

  def create
    @book      = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @books     = Book.all
    @book.user = current_user
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@books = Book.find(params[:id])
  	@books.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  # def search
  # @user_or_book = params[:option]
  # @how_search = params[:choice]
  # if @user_or_book = "1"
  #   @users = User.search(params[:search],@user_or_book, @how_search)
  # else @user_or_book = "2"
  #   @user.books = Book.all
  #   @books = Book.search(params[:search],@user_or_book, @how_search)
  # end
  #   render "searches/search"
  # end

  private

  def baria_user
    @book = Book.find(params[:id])
    @user = @book.user
    if @user != current_user
    redirect_to books_path
    end
  end
  #url直接防止　メソッドを自己定義してbefore_actionで発動。#

  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class='body'>
  <div class='container'>
    <div class='row'>
      <div class='col-md-6 col-md-offset-3'>

        <h1>Editing Book</h1>

        <!-- エラーメッセージ表示-->
        <%= render "template/error_messages" ,obj:@book %>
        <!-- エラーメッセージ表示-->

        <%= render 'newform', book: @book %>

        <%= link_to "Show", @book, class: "book_#{@book.id}" %> |
        <%= link_to "Back", books_path, class: "back" %>

      </div>

      <div class='col-md-3'></div>

   </div>
  </div>
</div>

<footer>
<%= render "template/footer" %>
</footer>

app/views/books/index.html.erb
<div class='body'>
  <div class='container'>

    <!-- エラーメッセージ表示-->
    <%= render "template/error_messages" ,obj:@book %>
    <!-- エラーメッセージ表示-->

    <div class='row'>
	    <div class='col-xs-3'>

	      <h2>User info</h2>
	      <%= render 'users/profile', user: current_user %>
		    <!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->
		    <div class='row'>
          <% if current_user.followed_by?(current_user) %>
            <%= link_to 'フォローを外す',user_relationships_path(user_id:current_user.id), method: :delete, class: "btn btn-primary col-xs-6" %>
          <% else %>
            <%= link_to 'フォローする',user_relationships_path(user_id:current_user.id),method: :post, class: "btn btn-success col-xs-6" %>
          <% end %>
        </div>

	      <h2>New book</h2>
	      <%= render 'newform', book: @book %>

	    </div>

	    <div class='col-xs-9'>

		    <h2>Books index</h2>
		    <!--books一覧 -->
		    <table class="table table-hover table-inverse">
			    <thead>
				  <tr>
					  <th></th>
					  <th>Title</th>
					  <th>Opinion</th>
					  <th colspan="3"></th>
				  </tr>
			    </thead>

			    <tbody>
				  <% @books.each do |book| %>
				  <tr>
					  <td>
						  <%= link_to(book.user) do %>
						  <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:"50x50") %>
						  <% end %>
					  </td>
					  <td>
					  	<%= link_to book.title, book, class: "book_#{book.id}" %>
					  </td>
					  <td>
					  	<%= book.body %>
					  </td>
					  <td>
					  	<% if book.favorited_by?(current_user) %>
					  	<!-- favoriteを消す！！ -->
					  	  <%= link_to book_favorites_path(book_id: book.id),method: :delete do %>
					  	  <i class="fa fa-heart" aria-hidden="true" style="color: black;"></i>
					  	  <%= book.favorites.count %>
					  	  <% end %>
					  	<% else %>
					  	<!-- favoriteを増やす！！ -->
					  	  <%= link_to book_favorites_path(book_id: book.id),method: :post do %>
					  	  <i class="fa fa-heart-o" aria-hidden="true" style="color: black;"></i>
					  	  <%= book.favorites.count %>
					  	  <% end %>
					  	<% end %>
					  </td>
					  <td>
					  	<p>コメント数：<%= book.book_comments.count %><p>
					  </td>
				  </tr>
				  <% end %>
			    </tbody>
		    </table>


		  <!--books一覧 -->
      </div>

	  </div>
  </div>
</div>

<footer>
<%= render "template/footer" %>
</footer>

app/views/books/show.html.erb
<div class='body'>
  <div class='container'>
    <div class='row'>
	    <div class='col-xs-3'>

		    <h2>User info</h2>
		    <%= render 'users/profile', user: @user %>

          <div class='row'>
            <% if current_user != @user %>
              <% if @user.followed_by?(current_user) %>
              <%= link_to 'フォローを外す',user_relationships_path(user_id:@user.id), method: :delete, class: "btn btn-primary col-xs-6" %>
            <% else %>
              <%= link_to 'フォローする',user_relationships_path(user_id:@user.id),method: :post, class: "btn btn-success col-xs-6" %>
              <% end %>
            <% end %>
          </div>

		    <h2>New book</h2>
		    <%= render 'newform', book: @book %>

	    </div>

	    <div class="col-xs-9">
		    <h2>Book detail</h2>

		    <table class="table">
				  <tr>
					  <td>
						  <%= link_to (@books.user) do %>
						  <%= attachment_image_tag(@books.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:"100x100") %><br>
						  <%= @books.user.name %>
						  <% end %>
					  </td>
					  <td>
						  <%= link_to @books.title, @books %>
					  </td>
					  <td>
						  <%= @books.body %>
					  </td>
					  <td>
					  	<% if @books.favorited_by?(current_user) %>
					  	  <%= link_to book_favorites_path(book_id: @books),method: :delete do %>
					  	  <i class="fa fa-heart" aria-hidden="true" style="color: black;"></i>
					  	  <%= @books.favorites.count %>
					  	  <% end %>
					  	<% else %>
					  	  <%= link_to book_favorites_path(book_id: @books),method: :post do %>
					  	  <i class="fa fa-heart-o" aria-hidden="true" style="color: black;"></i>
					  	  <%= @books.favorites.count %>
					  	  <% end %>
					  	<% end %>
					  </td>
					  <td>
					  	<p>コメント数：<%= @books.book_comments.count %><p>
					  </td>
					    <% if @books.user == current_user %>
					  <td>
						  <%= link_to "Edit",edit_book_path(@books), class: "btn-sm btn-success edit_book_#{@books.id}" %>
					  </td>
					  <td>
						  <%= link_to "Destroy",@books, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@books.id}" %>
						  <% end %>
					  </td>
				  </tr>
			  </table>

          <%= form_for ([@books,@book_comment]) do |f| %>
          <%= f.text_area :comment %>
          <%= f.submit "送信" %>
          <% end %>

　　　　　　<% @book_comments.each do |comment| %>
          <table>
          <tr>
            <td>
              <%= comment.comment %>
            </td>
            <% if @books.user == current_user %>
            <td>
            	 <%= link_to "Destroy",book_book_comments_path(book_id: @books,comment_id:comment.id),method: :delete %>
						</td>
						<% end %>
						<% end %> 
          </tr>
          </table>

      </div>

	  </div>
  </div>
</div>

<footer>
<%= render "template/footer" %>
</footer>