config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users

  root 'homes#top'
  get 'home/about' => 'homes#about'

  resources :books, only:[:index, :show, :edit, :create, :update, :destroy] do
   resource :favorites, only: [:create, :destroy]
   resource :book_comments, only: [:create, :destroy]
  end

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  get "search" => "searches#search"

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

 def search
  @user_or_book = params[:option]
  @how_search = params[:choice]
    if @user_or_book == "1"
      @users = User.search(params[:search],@user_or_book, @how_search)
    else
      @books = Book.search(params[:search],@user_or_book, @how_search)
    end
    render "searches/search"
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_searchform.html.erb
  <%= form_tag(search_path, :method => 'get') do %>
    <%= text_field_tag :search %>
    <%= select_tag(:option, options_for_select([["User","1"],["Book","2"]])) %>
    <%= select_tag(:choice, options_for_select([["完全一致","1"],["前方一致","2"],["後方一致","3"],["部分一致","4"]])) %>
    <%= submit_tag '検索', :nil => nil %>
  <% end %>

app/views/searches/search.html.erb
<div class='body'>
  <div class='conteiner'>
    <div clsaa='row'>
      <div class='col-md-offset-1 col-md-6'>

        <% if @user_or_book == "1" %>
          <h1>User</h1>
            <table class="table">
	        <thead>
		      <tr>
			      <th>image</th>
			      <th>name</th>
			      <th colspan="3"></th>
		      </tr>
	        </thead>

	        <tbody>
		        <% @users.each do |user| %>
		      <tr>
			      <td>
                <%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:"50x50") %>
            </td>
			      <td>
              <%= user.name%>
            </td>
            <td>
            <td>
              <p>フォロー数：<%=  user.followings.count %><p>
            </td>
            <td>
              <p>フォロワー数：<%= user.followers.count %><p>
            </td>
            <td>
              <% if user.followed_by?(current_user) %>
                <%= link_to 'フォローを外す',user_relationships_path(user_id:user.id), method: :delete %>
              <% else %>
                <%= link_to 'フォローする',user_relationships_path(user_id:user.id),method: :post %>
              <% end %>
            </td>
			      <td>
              <%= link_to "Show", user, class: "user_#{user.id}" %>
            </td>
		      </tr>
		      <% end %>
	        </tbody>
        </table>
        <!--users一覧 -->
        <% else %>
          <h2>Books index</h2>
		    <!--books一覧 -->
		    <table class="table table-hover table-inverse">
			    <thead>
				  <tr>
					  <th></th>
					  <th>Title</th>
					  <th>Opinion</th>
					  <th colspan="3"></th>
				  </tr>
			    </thead>

			    <tbody>
				  <% @books.each do |book| %>
				  <tr>
					  <td>
						  <%= link_to(book.user) do %>
						  <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:"50x50") %>
						  <% end %>
					  </td>
					  <td>
					  	<%= link_to book.title, book, class: "book_#{book.id}" %>
					  </td>
					  <td>
					  	<%= book.body %>
					  </td>
					  <td>
					  	<% if book.favorited_by?(current_user) %>
					  	<!-- favoriteを消す！！ -->
					  	  <%= link_to book_favorites_path(book_id: book.id),method: :delete do %>
					  	  <i class="fa fa-heart" aria-hidden="true" style="color: black;"></i>
					  	  <%= book.favorites.count %>
					  	  <% end %>
					  	<% else %>
					  	<!-- favoriteを増やす！！ -->
					  	  <%= link_to book_favorites_path(book_id: book.id),method: :post do %>
					  	  <i class="fa fa-heart-o" aria-hidden="true" style="color: black;"></i>
					  	  <%= book.favorites.count %>
					  	  <% end %>
					  	<% end %>
					  </td>
					  <td>
					  	<p>コメント数：<%= book.book_comments.count %><p>
					  </td>
				  </tr>
				  <% end %>
			    </tbody>
		    </table>
        <% end %>


      </div>
    </div>
  </div>
</div>