config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users

  root 'homes#top'
  get 'home/about' => 'homes#about'

  resources :books, only:[:index, :show, :edit, :create, :update, :destroy] do
   resource :favorites, only: [:create, :destroy]
   resource :book_comments, only: [:create, :destroy]
  end

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  get "search" => "searches#search"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	belongs_to :user

	has_many :favorites,dependent: :destroy
  def favorited_by?(user)
  	favorites.where(user_id: user.id).exists?
  end

  has_many :book_comments,dependent: :destroy

  def Book.search(search, user_or_book, how_search)
    if user_or_book == "2"
      if how_search == "1"
        Book.where(['title LIKE ?',"#{search}"])
      elsif how_search == "2"
        Book.where(['title LIKE ?',"#{search}%"])
      elsif how_search == "3"
        Book.where(['title LIKE ?',"%#{search}"])
      elsif how_search == "4"
        Book.where(['title LIKE ?',"%#{search}%"])
      else
        Book.all
      end
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  validates :comment,  presence: true

  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"
	validates :following_id, presence: true
  validates :follower_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name,  presence: true, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def User.search(search, user_or_book, how_search)
    if user_or_book == "1"
      if how_search == "1"
        User.where(['name LIKE ?',"#{search}"])
      elsif how_search == "2"
        User.where(['name LIKE ?',"#{search}%"])
      elsif how_search == "3"
        User.where(['name LIKE ?',"%#{search}"])
      elsif how_search == "4"
        User.where(['name LIKE ?',"%#{search}%"])
      else
        User.all
      end
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :baria_user, only: [:edit]

  def show
    @book         = Book.new
    @books        = Book.find(params[:id])
    @user         = @books.user
    @book_comment = BookComment.new
    @book_comments = @books.book_comments
  end

  def index
    @books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book  = Book.new
    @user = current_user
  end

  def create
    @book      = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @books     = Book.all
    @book.user = current_user
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@books = Book.find(params[:id])
  	@books.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  # def search
  # @user_or_book = params[:option]
  # @how_search = params[:choice]
  # if @user_or_book = "1"
  #   @users = User.search(params[:search],@user_or_book, @how_search)
  # else @user_or_book = "2"
  #   @user.books = Book.all
  #   @books = Book.search(params[:search],@user_or_book, @how_search)
  # end
  #   render "searches/search"
  # end

  private

  def baria_user
    @book = Book.find(params[:id])
    @user = @book.user
    if @user != current_user
    redirect_to books_path
    end
  end
  #url直接防止　メソッドを自己定義してbefore_actionで発動。#

  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
		favorite.save
		redirect_to request.referer
	end

	def destroy
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: book.id)
		favorite.destroy
		redirect_to request.referer
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

 def search
  @user_or_book = params[:option]
  @how_search = params[:choice]
    if @user_or_book == "1"
      @users = User.search(params[:search],@user_or_book, @how_search)
    else
      @books = Book.search(params[:search],@user_or_book, @how_search)
    end
    render "searches/search"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:update,:edit]

  def show
    @user  = User.find(params[:id])
    @books = @user.books
    @book  = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
    @users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
    @book  = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
    @user = current_user
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user  = User.find(params[:id])
    @books = @user.books
    @book  = Book.new
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <!--ヘッダーの記述-->
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
              <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
              <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books' %></li>
              <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
              <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
              <!-- routesを変更したのでpathも変更する！！ -->
              <li><%= link_to ' Sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
              <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <!--ヘッダーの記述-->
    <div class="container">
      <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->
    </div>

      <% if user_signed_in? %>
      <div class='row'>
        <div class='col-xs-8 col-xs-offset-4'>
          <%= render 'searches/searchform' %>
          </div>
      </div>
      <% end %>

    <body>
      <%= yield %>
    </body>
    <!-- header内にbodyを入れない、それからyieldの記述がないためviewが呼び出せない！！ -->
</html>

app/views/template/_error_messages.html.erb
    <% if obj.errors.any? %>
    <h3><%= obj.errors.count %>error occurrence</h3>
      <ul>
		    <% obj.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
		    <% end %>
	    </ul>
    <% end %>

app/views/template/_footer.html.erb
<div clss='container'>
  <div class='row'>
    <div class='col-xs-3 col-xs-offset-9'>
      <p>CopyRight Infratop.inc.</p>
    </div>
  </div>
</div>